"""making some varchar fields larger

Revision ID: 02ce59f0414f
Revises: 3cfeae58081e
Create Date: 2020-08-24 13:06:51.622860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ce59f0414f'
down_revision = '3cfeae58081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'movements',
               existing_type=sa.VARCHAR(length=244),
               type_=sa.String(length=400),
               existing_nullable=True)
    op.alter_column('piece', 'percussion',
               existing_type=sa.VARCHAR(length=244),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'percussion',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=244),
               existing_nullable=True)
    op.alter_column('piece', 'movements',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=244),
               existing_nullable=True)
    # ### end Alembic commands ###
