"""added a lot of things

Revision ID: 106f4769b94a
Revises: 
Create Date: 2020-02-08 00:11:44.025119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106f4769b94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('years', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('details', sa.String(length=244), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composer_name'), 'composer', ['name'], unique=True)
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=244), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('movements', sa.String(length=244), nullable=True),
    sa.Column('movement_duration', sa.String(length=244), nullable=True),
    sa.Column('instrumentation', sa.String(length=400), nullable=True),
    sa.Column('soloists', sa.String(length=244), nullable=True),
    sa.Column('percussion', sa.String(length=244), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('studied', sa.Boolean(), nullable=True),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher_pieces',
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher_pieces')
    op.drop_table('piece')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_composer_name'), table_name='composer')
    op.drop_table('composer')
    # ### end Alembic commands ###
