"""made varcahrs bigger AGAIN

Revision ID: 14340f5827a6
Revises: 02ce59f0414f
Create Date: 2020-08-24 13:53:45.864068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14340f5827a6'
down_revision = '02ce59f0414f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'instrumentation',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('piece', 'movements',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('piece', 'notes',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('piece', 'percussion',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('piece', 'soloists',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'soloists',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=800),
               existing_nullable=True)
    op.alter_column('piece', 'percussion',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('piece', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
    op.alter_column('piece', 'movements',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('piece', 'instrumentation',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
