"""made the movements field bigger again

Revision ID: 178bbcd23fef
Revises: 14340f5827a6
Create Date: 2020-08-24 17:30:17.279259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178bbcd23fef'
down_revision = '14340f5827a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'movements',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'movements',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
