"""making changes?

Revision ID: 2c56311eddf5
Revises: bffaeb8b6ad7
Create Date: 2020-08-08 19:44:45.628716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c56311eddf5'
down_revision = 'bffaeb8b6ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'notes',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'notes',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
