""" added lots of new stuff

Revision ID: 3befa79d4383
Revises: 5a8be4a58d79
Create Date: 2020-02-10 22:29:41.132070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3befa79d4383'
down_revision = '5a8be4a58d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('studied', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('favorited_pieces',
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('piece', sa.Column('favorited_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece', 'user', ['favorited_by'], ['id'])
    op.drop_column('piece', 'need_to_learn')
    op.drop_column('piece', 'studied')
    op.drop_column('piece', 'favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('favorite', sa.BOOLEAN(), nullable=True))
    op.add_column('piece', sa.Column('studied', sa.BOOLEAN(), nullable=True))
    op.add_column('piece', sa.Column('need_to_learn', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_column('piece', 'favorited_by')
    op.drop_table('favorited_pieces')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
