"""extended character fields

Revision ID: 3cfeae58081e
Revises: 9a58345c28d8
Create Date: 2020-08-24 12:55:24.683169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfeae58081e'
down_revision = '9a58345c28d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('composer', 'details',
               existing_type=sa.VARCHAR(length=244),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('piece', 'soloists',
               existing_type=sa.VARCHAR(length=244),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'soloists',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=244),
               existing_nullable=True)
    op.alter_column('composer', 'details',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=244),
               existing_nullable=True)
    # ### end Alembic commands ###
