"""new fields

Revision ID: 5a8be4a58d79
Revises: 551cf3a1fd7d
Create Date: 2020-02-09 07:31:44.602059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8be4a58d79'
down_revision = '551cf3a1fd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('favorite', sa.Boolean(), nullable=True))
    op.add_column('piece', sa.Column('need_to_learn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'need_to_learn')
    op.drop_column('piece', 'favorite')
    # ### end Alembic commands ###
