"""changed the favorites column, probably wont work

Revision ID: 789c039bde7c
Revises: bffaeb8b6ad7
Create Date: 2020-03-12 22:01:13.548251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789c039bde7c'
down_revision = 'bffaeb8b6ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('piece') as batch_op:
     #   batch_op.add_column(Column('notes1', String(1000)))
      #  batch_op.drop_column('notes')
    op.alter_column('piece', 'notes',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('piece', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
