"""empty message

Revision ID: 7ec2f4343332
Revises: 2c56311eddf5
Create Date: 2020-08-24 10:15:41.140165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec2f4343332'
down_revision = '2c56311eddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concert_title'), 'concert', ['title'], unique=False)
    op.create_table('concert_pieces',
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_pieces')
    op.drop_index(op.f('ix_concert_title'), table_name='concert')
    op.drop_table('concert')
    # ### end Alembic commands ###
