"""tried deleting the migration file

Revision ID: b6ef0bc601b7
Revises: 5a8be4a58d79
Create Date: 2020-02-23 21:40:21.729258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef0bc601b7'
down_revision = '5a8be4a58d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_body'), 'comment', ['body'], unique=True)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'piece', 'user', ['favorited_by'], ['id'])
    op.drop_column('piece', 'favorite')
    op.drop_column('piece', 'studied')
    op.drop_column('piece', 'need_to_learn')
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.add_column('piece', sa.Column('need_to_learn', sa.BOOLEAN(), nullable=True))
    op.add_column('piece', sa.Column('studied', sa.BOOLEAN(), nullable=True))
    op.add_column('piece', sa.Column('favorite', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_index(op.f('ix_comment_body'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
